# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - DOCKER_IMAGE={{ if index .Env "GITHUB_REPOSITORY"  }}{{ .Env.GITHUB_REPOSITORY }}{{ else }}peribolosmerger/peribolosmerger{{ end }}
project_name: peribolosmerger
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  mode: append
dockers:
  -
    image_templates:
      - "ghcr.io/{{ .Env.DOCKER_IMAGE }}:latest"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE }}:{{ .Tag }}"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE }}:v{{ .Major }}"
